image: node:alpine

before_script:
  - apk add --no-cache --update git openssh python python3 py3-pip make g++
  - npm install

cache:
  paths:
    - node_modules/

stages:
  - deploy

publish:
   stage: deploy
   only:
     - master
     - tags
   script:
     - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
     - echo 'unsafe-perm = true' >> ~/.npmrc
     - npm publish --registry https://registry.npmjs.org
